datamesh-web/Models/DataDomainModel.cs
using System.ComponentModel.DataAnnotations;

namespace datamesh_web.Models
{
    public class DataDomainModel
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Name is Required.")]
        [StringLength(40, ErrorMessage = "Name length can't be more than 40.")]
        [Display(Name = "Data Domain Name")]
        public string? Name { get; set; }
        [Required(ErrorMessage = "Key is Required.")]
        [StringLength(20, ErrorMessage = "Key length can't be more than 20.")]
        [Display(Name = "Data Domain Key")]
        public string Key { get; set; }
        [Required(ErrorMessage = "Name Abbreviation Long is Required.")]
        [Display(Name = "Abbreviation Long")]
        public string NameAbbreviationLong { get; set; }
        [Required(ErrorMessage = "Name Abbreviation Short is Required.")]
        [StringLength(4, ErrorMessage = "Abbreviation Short length can't be more than 4.")]
        [Display(Name = "Abbrevation Short")]
        public string NameAbbreviationShort { get; set; }
        [Required(ErrorMessage = "SubscriptionName is Required.")]
        [Display(Name = "Subscription Name")]
        public string SubscriptionName { get; set; }
        [Required(ErrorMessage = "SubscriptionId is Required.")]
        [Display(Name = "Subscription Id")]
        public Guid SubscriptionId { get; set; }
        [Required(ErrorMessage = "DevOpsProjectName is Required.")]
        [Display(Name = "DevOps Project")]
        public string DevOpsProjectName { get; set; }
    }
}

datamesh-web/Models/DataproductModel.cs
using System.ComponentModel.DataAnnotations;

namespace datamesh_web.Models
{
    public class DataproductModel
    {
        public Guid Id { get; set; }
        [Display(Name = "Dataproduct Name")]
        public string? Name { get; set; }
        [Display(Name = "Dataproduct Key")]
        public string Key { get; set; }
    }
}

datamesh-web/Models/ErrorViewModel.cs
namespace datamesh_web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

datamesh-web/Controllers/DataDomainController.cs
using Microsoft.AspNetCore.Mvc;
using datamesh_web.Interfaces;
using datamesh_web.Models;

namespace datamesh_web.Controllers
{
    public class DataDomainController : Controller
    {
        private readonly IDataDomainService _service;
        private readonly ILogger<DataDomainController> _logger;

        public DataDomainController(IDataDomainService service, ILogger<DataDomainController> logger)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
            _logger = logger;
        }

        public async Task<IActionResult> DataDomainIndex()
        {
            var datadomains = await _service.Find();
            return View(datadomains);
        }

        public async Task<IActionResult> DataDomainView(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datadomain = await _service.FindById(id);
            return View(datadomain);
        }

        // GET: DataDomain/DataDomainCreate
        [HttpGet]
        public IActionResult DataDomainCreate()
        {
            return View();
        }

        // I want to create a new DataDomain
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DataDomainCreate(
            [Bind("Key,Name,NameAbbreviationLong,NameAbbreviationShort,SubscriptionName,SubscriptionId,DevOpsProjectName")] DataDomainModel datadomain)
        {
            if (ModelState.IsValid)
            {
                await _service.Add(datadomain);
                return RedirectToAction(nameof(DataDomainIndex));
            }
            return View(datadomain);
        }
    }
}

datamesh-web/Controllers/DataproductController.cs
using Microsoft.AspNetCore.Mvc;
using datamesh_web.Interfaces;
using datamesh_web.Models;

namespace datamesh_web.Controllers
{
    public class DataproductController : Controller
    {
        private readonly IDataproductService _service;
        private readonly ILogger<DataproductController> _logger;

        public DataproductController(IDataproductService service, ILogger<DataproductController> logger)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
            _logger = logger;
        }

        // GET: Dataproduct
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Dataproducts = await _service.Find();
            return View(Dataproducts);
        }

        public async Task<IActionResult> DataproductView(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Dataproduct = await _service.FindById(id);
            return View(Dataproduct);
        }

        // GET: Dataproduct/DataproductCreate
        [HttpGet]
        public IActionResult DataproductCreate()
        {
            return View();
        }

        // I want to create a new Dataproduct
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DataproductCreate(
            [Bind("Key,Name,NameAbbrevationLong,NameAbbreviationShort,SubscriptionName,SubscriptionId,DevOpsProjectName")] DataproductModel Dataproduct)
        {
            if (ModelState.IsValid)
            {
                await _service.Add(Dataproduct);
                return RedirectToAction(nameof(Index));
            }
            return View(Dataproduct);
        }
    }
}

datamesh-web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using datamesh_web.Models;

namespace datamesh_web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

datamesh-web/Views/DataDomain/DataDomainCreate.cshtml
@model DataDomainModel

@using (Html.BeginForm("DataDomainCreate", "DataDomain", FormMethod.Post))
{

<div class="container">
    <div class="row px-3 my-4 py-2 rounded-15">
        <h3>Create a new Datadomain</h3>
    </div>
</div>

<div class="container">
    <div class="row px-3 py-4 rounded-5 bg-white">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    
    <div class="row px-3 py-4 rounded-5 bg-white">
        <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="Key" class="form-label"></label>
                <input asp-for="Key" class="form-control" />
                <span asp-validation-for="Key" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="NameAbbreviationLong" class="form-label"></label>
                <input asp-for="NameAbbreviationLong" class="form-control" />
                <span asp-validation-for="NameAbbreviationLong" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="NameAbbreviationShort" class="form-label"></label>
                <input asp-for="NameAbbreviationShort" class="form-control" />
                <span asp-validation-for="NameAbbreviationShort" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="SubscriptionName" class="form-label"></label>
                <input asp-for="SubscriptionName" class="form-control" />
                <span asp-validation-for="SubscriptionName" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="SubscriptionId" class="form-label"></label>
                <input asp-for="SubscriptionId" class="form-control" />
                <span asp-validation-for="SubscriptionId" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <label asp-for="DevOpsProjectName" class="form-label"></label>
                <input asp-for="DevOpsProjectName" class="form-control" />
                <span asp-validation-for="DevOpsProjectName" class="text-danger"></span>
        </div>
        <div class="mb-3">
                <input type="submit" value="Submit" class="btn btn-outline-success my-3"/>
        </div>
    </div>
</div>

}

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

datamesh-web/Views/DataDomain/DataDomainIndex.cshtml
@model IEnumerable<datamesh_web.Models.DataDomainModel>

<div class="container">
    <div class="row px-3 my-4 py-2 rounded-15">
        <h3>Datadomain(s)</h3>
    </div>
</div>

<div class="container">
    <div class="row">
        <p>
            <a class="btn btn-outline-success my-3" asp-action="DataDomainCreate">Create New</a>
        </p>
    </div>
    <div class="row px-3 py-4 rounded-5 bg-white">
        <table class="table table-striped table-hover table-sm">
            <tdead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Key</th>
                    <th>Subscription Id</th>
                    <th>Actions</th>
                </tr>
            </tdead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Key</td>
                            <td>@item.SubscriptionId</td>
                            <td>
                                <a class="nav-link text-dark" asp-area="" asp-controller="DataDomain" asp-action="DataDomainView" asp-route-id="@item.Id">
                                    <i class="fa fa-eye"></i>
                                    View
                                </a>
                            </td>  
                        </tr>
                    }
                </tbody>
        </table>
    </div>
</div>

datamesh-web/Views/DataDomain/DataDomainView.cshtml
@model DataDomainModel

<div class="container">
    <div class="row px-3 my-4 py-2 rounded-15">
        <h3>Datadomain - @Model.Name</h3>
    </div>
</div>

<div class="container">
    <div class="row px-3 py-4 rounded-5 bg-white">
        <table class="table table-hover table-sm">
            <thead>
                <tr>
                    <th>Attribute</th>
                    <th>Value</th>
                </tr>
            </thead>
                <tbody>
                    <tr>
                        <td>Id</td>
                        <td>@Model.Id</td>
                    </tr>
                    <tr>
                        <td>Name</td>
                        <td>@Html.DisplayFor(model => model.Name)</td>
                    </tr>
                    <tr>
                        <td>Key</td>
                        <td>@Model.Key</td>
                    </tr>
                    <tr>
                        <td><label asp-for="NameAbbreviationLong" class="form-label"></label></td>
                        <td>@Html.DisplayFor(model => model.NameAbbreviationLong)</td>
                    </tr>
                    <tr>
                        <td><label asp-for="NameAbbreviationShort" class="form-label"></label></td>
                        <td>@Html.DisplayFor(model => model.NameAbbreviationShort)</td>
                    </tr>
                    <tr>
                        <td><label asp-for="SubscriptionName" class="form-label"></label></td>
                        <td>@Html.DisplayFor(model => model.SubscriptionName)</td>
                    </tr>
                    <tr>
                        <td><label asp-for="SubscriptionId" class="form-label"></label></td>
                        <td>@Html.DisplayFor(model => model.SubscriptionId)</td>
                    </tr>
                    <tr>
                        <td><label asp-for="DevOpsProjectName" class="form-label"></label></td>
                        <td>@Html.DisplayFor(model => model.DevOpsProjectName)</td>
                    </tr>
                </tbody>
        </table>
    </div>
</div>

datamesh-web/Views/Dataproduct/Index.cshtml
@model IEnumerable<datamesh_web.Models.DataproductModel>

<div class="container">
    <div class="row px-3 my-4 py-2 rounded-15">
        <h3>Dataproduct(s)</h3>
    </div>
</div>

<div class="container">
    <div class="row">
        <p>
            <a class="btn btn-outline-success" asp-action="DataproductCreate">Create New</a>
        </p>
    </div>
    <div class="row px-3 py-4 rounded-5 bg-white">
        <table class="table table-striped table-hover table-sm">
            <tdead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Key</th>
                    <th>Actions</th>
                </tr>
            </tdead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Key</td>
                            <td>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dataproduct" asp-action="DataproductView" asp-route-id="@item.Id">
                                    <i class="fa fa-eye"></i>
                                    View
                                </a>
                            </td>  
                        </tr>
                    }
                </tbody>
        </table>
    </div>
</div>

datamesh-web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row px-3 my-4 py-2 rounded-15">
        <h3>Data Mesh</h3>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h4>What is Data Mesh?</h4>
            <p>
                Data Mesh is a new paradigm for data processing. It is a way to build a data platform that is scalable, flexible, and secure.
            </p>
        </div>
    </div>
</div>

datamesh-web/Views/Shared/_DatameshLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - datamesh_web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/fontawesome/css/fontawesome.css" rel="stylesheet">
    <link href="~/lib/fontawesome/css/brands.css" rel="stylesheet">
    <link href="~/lib/fontawesome/css/solid.css" rel="stylesheet">
    <link href="~/lib/fontawesome/css/regular.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-white border">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pt-5 pb-3 mb-md-5 me-md-auto text-grey text-decoration-none">
                    <i class="fa-solid fa-cube"></i>
                    <span class="fs-5 d-none d-sm-inline">&nbsp;datamesh</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a class="nav-link text-success" asp-area="" asp-controller="Home" asp-action="Index">
                            <i class="fa-solid fa-bars"></i> <span class="ms-1 d-none d-sm-inline">Modules</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Dataproduct" asp-action="Index">
                            <i class="fa-solid fa-industry"></i> Dataproduct
                        </a>
                    </li>
                    <li class="nav-link">
                        <a class="nav-link text-dark" asp-area="" asp-controller="DataDomain" asp-action="DataDomainIndex">
                            <i class="fa-solid fa-industry"></i> DataDomain
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col py-3 border bg-light">
            @RenderBody()
        </div>
    </div>
</div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

datamesh-web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - datamesh_web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/datamesh_web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">datamesh_web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dataproduct" asp-action="DataproductIndex">Dataproduct</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DataDomain" asp-action="DataDomainIndex">DataDomain</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - datamesh_web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>